### 결제
POST http://localhost:8080/api/point-withdraw/payment/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNkQG5hdmVyLmNvbSIsInJvbGVzIjoiTUVNQkVSIiwiaWF0IjoxNzA4MDE0Mjc2LCJleHAiOjE3MDgwMTc4NzZ9.dBxU55-OK3FrXDkMNUDPd5vdCiVt9XT9YCBIXiRe-TM


### 포인트 출금 내역 조회
GET http://localhost:8080/api/point-withdraw/member
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNkQG5hdmVyLmNvbSIsInJvbGVzIjoiTUVNQkVSIiwiaWF0IjoxNzA3OTI0MDk4LCJleHAiOjE3MDc5Mjc2OTh9.RPJ3cza5YEGAtq-nETOw70Mmc6IVoaYEac205DKCzJg
