### 챌린지 등록
POST http://localhost:8080/api/challenge/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNkQG5hdmVyLmNvbSIsInJvbGVzIjoiTUVNQkVSIiwiaWF0IjoxNzA2ODYwNzU4LCJleHAiOjE3MDY4NjQzNTh9.2w-L6Sw0b2b0ZMpbSuxxQ5xjJPUo_wOFypVubIKEk3Q

{
  "challengeName": "24년 03월 챌린지",
  "challengeStartDate": "2024-03-01"
}


### 전체 챌린지 조회
GET http://localhost:8080/api/challenge/total
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNkQG5hdmVyLmNvbSIsInJvbGVzIjoiTUVNQkVSIiwiaWF0IjoxNzA2ODYwNzU4LCJleHAiOjE3MDY4NjQzNTh9.2w-L6Sw0b2b0ZMpbSuxxQ5xjJPUo_wOFypVubIKEk3Q


### 챌린지 삭제
DELETE http://localhost:8080/api/challenge/delete/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmNkQG5hdmVyLmNvbSIsInJvbGVzIjoiTUVNQkVSIiwiaWF0IjoxNzA2ODYwNzU4LCJleHAiOjE3MDY4NjQzNTh9.2w-L6Sw0b2b0ZMpbSuxxQ5xjJPUo_wOFypVubIKEk3Q